### PR TITLE
Buttons in gitlab on the merge_request view

### PR DESCRIPTION
**Pull request by slava-v**
Separate the onclick handlers and include buttons for merge requests views in gitlab

### CODE REVIEW

**Comment by maximmig** [comment]
Hi @slava-v, thanks for the PR. Could you please describe its purpose in more detail and attach any screenshots to see what functionality your changes will add? Cheers.

**Comment by slava-v** [comment]
> Hi @slava-v, thanks for the PR. Could you please describe its purpose in more detail and attach any screenshots to see what functionality your changes will add? Cheers.

Hi @maximmig, thanks for asking, i also forgot to push latest changes I had :facepalm: 

Essentially this adds the "open in ..." buttons not only when viewing a single file, but also, from the Merge request view, for GitLab.

image


I know my changes could not be ideal, but please let me know if there is anything wrong so I could improve.

Thanks!

**Comment by slava-v** [comment]
@maximmig , i've updated the implementation with using observer, could you check please ?

**Review by randydwhitephotography — APPROVED** [review]

**Review by randydwhitephotography — APPROVED** [review]

**Review by randydwhitephotography — APPROVED** [review]

**Comment by maximmig** [comment]
Hi @slava-v, sorry for super late reply 😔 The issue you're addressing in the PR was fixed in the past, appeared again, and eventually fixed one more time 😅 could you please pull the last changes and see if it works for you? 🙏 Thanks!

**Pull request closed without merging**
