### PR TITLE
Moving the Action inside the clone pop-up modal in new github

### PR DESCRIPTION
**Pull request by stenalpjolly**
Testing a new idea on moving the actions inside the clone modal
       
Screenshot 2020-11-03 at 3 00 39 PM

### CODE REVIEW

**Comment by stenalpjolly** [comment]
FYI @yaegor @yole @topka @shafirov

**Comment by stenalpjolly** [comment]
@maximmig

**Comment by yole** [comment]
Do you expect the CEO of JetBrains to make any decisions about your commit personally? Please avoid mentioning random people who are in no way involved in the project you want to contribute to.

**Comment by stenalpjolly** [comment]
> Do you expect the CEO of JetBrains to make any decisions about your commit personally? Please avoid mentioning random people who are in no way involved in the project you want to contribute to.

I saw him as one of the reviewers in an old PR.

**Comment by maximmig** [comment]
> I saw him as one of the reviewers in an old PR.

Hi @stenalpjolly, I will look into this as soon as I have enough time for this, thanks.

**Comment by yole** [comment]
I'm pretty sure that I never reviewed any PRs in this repo. And the fact that I reviewed some PRs somewhere at some time doesn't mean that you're free to spam me and my colleagues.

**Comment by stenalpjolly** [comment]
@maximmig Any update?

**Comment by stenalpjolly** [comment]
@maximmig Can you please review the changes?

**Comment by stenalpjolly** [comment]
@maximmig Can you please check this and move this to closure?

**Comment by maximmig** [comment]
Hi @stenalpjolly! We have discussed the suggested changes and came to the conclusion that if we implement them, it will have a negative impact on the user experience (more mouse clicks) and also on the discoverability of our IDEs (the clone buttons will be hidden). We understand that the current solution is not ideal and we plan to implement another one as soon as we have enough time for it, which will probably be to move our clone buttons to a separate floating panel, but this is not certain. Thank you!

**Comment by stenalpjolly** [comment]
@maximmig Thank you for the update. Looking forward to the next version. Please do let me know if you need any help.

**Pull request closed without merging**
