### PR TITLE
Update buttons placement

### PR DESCRIPTION
**Pull request by princed**
Button placement is a bit broken with recent GitHub markup changes
image
This PR puts them back in place.

P.S. Also updated `yarn.lock` to make sure that only external registry is used in there.

### CODE REVIEW

**Comment by kropp** [comment]
Thanks, Eugene!

**Comment by princed** [comment]
@kropp Could you update it in stores?

**Comment by kropp** [comment]
Done, should be available soon.

**Comment by princed** [comment]
It works, thank you! 🔨🗃

**Pull request merged**
